# Generated by Django 4.1.6 on 2023-02-12 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_order_tax_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
    ]
